#include "Common.ush"

float4 OffsetAndSize;
Texture2D InputTex;
SamplerState InputTexSampler;

static const float FarPlane = 65500.f;

void MainPS(in VS2PS Input, out float4 OutColor : SV_Target0)
{
    float Current = InputTex.Sample(InputTexSampler, Input.Coord + OffsetAndSize.xy * float2(-1.0, 1.0)).r;
    if (Current > FarPlane)
        clip(FarPlane - Current);
    OutColor = float4(Current, 0.0, 0.0, 1.0);
}